### ISSUE TITLE
Relating to "metafy" coding

### ISSUE THREAD

**Issue by guobao2333** [ytoku/vizshhist#2]
您好。  
关于`metafy`这个编码我使用搜索引擎，甚至没有找到任何信息，但我通过搜索 `.zsh_history` 获得了一些信息。

原文来自zsh官网的邮件，其目的是在命令行中打印`.zsh_history`文件的内容，但有些内容会出现乱码。开发者的回复中提供了一个简单的程序源码用来实现其原文要求的功能。
虽然您的存储库提供了工具可以解决，但至少有几个点让我无法接受(可能也是大多数人的理由)  
1. 包安装工具太陌生了，我不想为一个不经常使用的东西浪费空间。(为什么不使用apt呢？)
2. 基于上一点，我可能并不会深入了解您的工具。

我的本意并不是为了说您不好，很感谢您的开源，但我认为为了让更多的人能够贡献和使用您的工具，上面的建议希望您能够有一些思考。

最后，因为这个个性化需求太少了，以至于搜索引擎没有结果，所以上面的建议可能忽略了也没关系……好吧我的意思是指，这只是一些建议，您也不一定需要采纳。

祝您有美好的一天。

**Comment by ytoku** [comment]
Hello,

I was lazy because I thought nobody except me used this tool. :melting_face:
Since this tool consists of a single binary file, I will not provide a deb package, but instead will provide pre-built binaries in [releases](https://github.com/ytoku/vizshhist/releases) page.

Thanks.
